docs/2.guide/2.directory-structure/1.components.md
=> 1.components.md / имена компонентов

docs/3.api/1.components/1.dev-only.md
=> 3.api/1.components/1.dev-only.md

docs/3.api/1.components/9.nuxt-img.md
Переведена страница /api/components/nuxt-img
=> translate: nuxt-img

docs/2.guide/1.concepts/9.code-style.md
https://github.com/translation-gang/nuxt/issues/36
feat(docs) Перевод раздела Code Style
=> feat(docs) Перевод раздела Code Style

docs/3.api/5.kit/15.examples.md
=> feat(docs) Перевод Examples

docs/3.api/5.kit/10.runtime-config.md
feat(docs) Перевод Runtime Config
=> feat(docs) Перевод Runtime Config

docs/1.getting-started/5.seo-meta.md
resolves #25 
Добавлен перевод раздела
=> feat(docs): Переведен раздел SEO and Meta (#25)

docs/3.api/2.composables/use-loading-indicator.md
resolves #87 
Добавлен перевод композабла useLoadingIndicator
=> feat(docs): Переведен раздел useLoadingIndicator (#87)

docs/3.api/3.utils/set-page-layout.md, docs/3.api/3.utils/set-response-status.md, docs/3.api/3.utils/show-error.md, docs/3.api/3.utils/update-app-config.md
resolves #98 
feat(docs) Перевод utils
=> feat(docs) Перевод utils

docs/3.api/1.components/6.nuxt-error-boundary.md
resolves https://github.com/translation-gang/nuxt/issues/51
Переведена страница /api/components/nuxt-error-boundary
=> feat(docs): перевод nuxt-error-boundary

docs/3.api/2.composables/use-head.md
resolves #86 
Переведен раздел useHead (#86)
=> feat(docs): Переведен раздел useHead (#86)

docs/3.api/2.composables/use-cookie.md
resolves #77 
Переведен раздел useCookie (#77)
=> feat(docs): Переведен раздел useCookie (#77)

docs/3.api/1.components/10.nuxt-picture.md
resolves https://github.com/translation-gang/nuxt/issues/54
Переведена страница /api/components/nuxt-picture
=> feat(docs): Перевод nuxt-picture

docs/3.api/1.components/11.teleports.md
resolves https://github.com/translation-gang/nuxt/issues/56 + https://github.com/translation-gang/nuxt/issues/55
Переведена страница /api/components/teleports
=> feat(docs): Перевод teleports

docs/3.api/1.components/7.nuxt-welcome.md
resolves https://github.com/translation-gang/nuxt/issues/52
Переведена страница /api/components/nuxt-welcome
=> feat(docs): Перевод nuxt-welcome

docs/1.getting-started/11.testing.md, docs/6.bridge/2.typescript.md, docs/6.bridge/4.plugins-and-middleware.md, docs/6.bridge/6.meta.md
resolves #145 
feat(docs) Перевод документации Bridge
=> feat(docs) Перевод документации Bridge

docs/1.getting-started/5.transitions.md, docs/6.bridge/8.nitro.md
resolves #144 
feat(docs) Перевод документации Nitro
=> feat(docs) Перевод документации Nitro

docs/1.getting-started/5.transitions.md, docs/5.community/7.changelog.md
resolves #140 
feat(docs) Перевод документации Релизы
=> feat(docs) Перевод документации Релизы

docs/2.guide/3.going-further/2.hooks.md
resolves https://github.com/translation-gang/nuxt/issues/61
Переведена страница docs/guide/going-further/hooks.md
=> feat(docs): Локализация docs/guide/going-further/hooks

docs/3.api/2.composables/use-nuxt-data.md
resolves https://github.com/translation-gang/nuxt/issues/89
Переведена страница docs/api/composables/use-nuxt-data.md
=> feat(docs): Локализация docs/api/composables/use-nuxt-data.md

docs/2.guide/2.directory-structure/1.composables.md
resolves #39
[docs/2.guide/2.directory-structure/1.composables.md](https://nuxt-ru.vercel.app/docs/guide/directory-structure/composables)
=> Локализация docs/2.guide/2.directory-structure/1.composables.md

docs/2.guide/2.directory-structure/1.layouts.md
resolves #40
[docs/2.guide/2.directory-structure/1.layouts.md](https://nuxt-ru.vercel.app/docs/guide/directory-structure/layouts)
=> Локализация docs/2.guide/2.directory-structure/1.layouts.md

docs/5.community/3.reporting-bugs.md
resolves #136 
Добавлен перевод статьи про сообщения о багах
=> feat(docs): Переведен раздел reporting bugs (#136)

docs/3.api/2.composables/use-preview-mode.md
resolves https://github.com/translation-gang/nuxt/issues/90
Переведена страница docs/api/composables/use-preview-mode.md
=> feat(docs): Локализация docs/api/composables/use-preview-mode.md

docs/2.guide/3.going-further/1.features.md
resolves #59 
Добавлен перево для features
=> feat(docs): Добавлен перевод для features (#59)

docs/3.api/2.composables/use-runtime-config.md
resolves https://github.com/translation-gang/nuxt/issues/93
Переведена страница docs/api/composables/use-runtime-config.md
=> feat(docs): Локализация docs/api/composables/use-runtime-config.md

docs/2.guide/3.going-further/9.debugging.md
resolves #66 
[docs/2.guide/3.going-further/9.debugging.md](https://nuxt-ru.vercel.app/docs/guide/going-further/debugging)
=> Локализация docs/2.guide/3.going-further/9.debugging.md (#66)

docs/1.getting-started/9.layers.md
resolves #251 
- Добавлен недостающий перевод docs/1.getting-started/9.layers.md
- Исправлены ошибки
=> feat(docs): Актуализация docs/1.getting-started/9.layers.md

docs/2.guide/2.directory-structure/1.components.md
resolves #252 
Добавлен недостающий перевод docs/2.guide/2.directory-structure/1.components.md
=> feat(docs): Актуализация docs/2.guide/2.directory-structure/1.components.md 

docs/3.api/3.utils/navigate-to.md
resolves #256 
Добавлен недостающий перевод docs/3.api/3.utils/navigate-to.md
=> feat(docs): Актуализация docs/3.api/3.utils/navigate-to.md

docs/3.api/1.components/3.nuxt-layout.md
[docs/3.api/1.components/3.nuxt-layout.md](https://nuxt-ru.vercel.app/docs/api/components/nuxt-layout)
=> Обновление перевода components/nuxt-layout

docs/3.api/2.composables/use-request-fetch.md
Переведена страница docs/3.api/2.composables/use-request-fetch.md
=> feat(docs): Локализация docs/3.api/2.composables/use-request-fetch.md

docs/1.getting-started/12.upgrade.md, docs/2.guide/3.going-further/1.experimental-features.md
https://nuxt-ru.vercel.app/docs/getting-started/upgrade
https://nuxt-ru.vercel.app/docs/guide/going-further/experimental-features
=> feat(docs): Актуализация новых частей
